### PR TITLE
OSReport: fix sending message when its larger than the buffer #205

### LINKED ISSUE #205: `SYS_Report` reads past buffer forever when string is longer than 256 bytes
## Bug Report

When trying to print a string that's longer than 256 bytes using `SYS_Report` (on Dolphin 2412, if that matters), it seems to skip the null terminator and keeps reading past the end of the string forever in an infinite loop (until it eventually crashes when it reaches unmapped memory).

Example repro that exhibits the issue:
```c
#include <ogc/system.h>

int main(void) {
  char buf[257];
  memset(buf, 'a', sizeof(buf));
  buf[256] = 0;
  SYS_Report("%s\n", buf);
  return 0;
}
```
(using any of the wii-examples setups)

### PR DESCRIPTION
**Pull request by DacoTaco**
should fix #205

### CODE REVIEW

File: libogc/sys_report.c [hunk 1]
```diff
@@ -99,19 +104,38 @@ void SYS_STDIO_Report(bool use_stdout)
...
+		char* tmp = (char*)realloc(buffer, write_len);
+		if(tmp == NULL)
+			break;
+
+		buffer = tmp;
+
+		va_start(args, fmt_);
+		len = vsnprintf(buffer, write_len, fmt_, args);
+		va_end(args);
+		if(len >= write_len)
```
Comment (WinterMute) [inline libogc/sys_report.c:124]: also check for negative return indicating an error & bail out

Comment (WinterMute) [inline libogc/sys_report.c:124]: also check for negative return & bail out

Comment (DacoTaco) [reply libogc/sys_report.c]: resolved, added len > 0 check because the signed difference could again cause issues here :)

**Comment by WinterMute** [comment]
lgtm
